import {useState, useEffect, useRef} from 'react'
import '../../index.css'
import StoredChat from './StoredChat';
import { getAllStoredChats } from '../../utils';

function ChatWindow() {

    const [userInput, setUserInput] = useState('');
    const [chatLog, setChatLog] = useState([]);
    const [loading, setLoading] = useState(false);
    //boolean to check if a chat has been selected or not
    const [chatSelectedFlag,setChatSelectedFlag] = useState(false);
    //list of all chats created by the user
    const [allCreatedChats,setAllCreatedChats] = useState([]);

    //the conversation id of the current selected chat (not the conversation id of the backend)
    const [currentChatID,setCurrentChatID] = useState(null)
    //check if user is currently creating a chat or not
    const [creatingChat, setCreatingChat] = useState(false)

    const currentChatIDRef = useRef(null)

    //using useRef instead of useState to update value of streamed content without re-rendering
    const streamedTextRef = useRef("");

    const chatWindowBottomRef = useRef(null);





    //const queryID
    const [queryID, setQueryID] = useState(null)


    //controllerRef flag to indicate that
    const controllerRef = useRef(false)

    //tracking if user has pressed the cancel button
    const cancelledRef = useRef(null)


    // Load chat history for current selected chat
    useEffect(() => {


    }, []);


    //Load previously created chats
    useEffect(()=>{




         getAllStoredChats(setAllCreatedChats);
        

    },[])


    
    




    //every time a new message is in the chat, or a different chat is selected, scroll to the bottom of the chat area (everytime chatlog changes)
    useEffect(()=>{

        if(chatWindowBottomRef){
            chatWindowBottomRef.current.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'start' })

        }



    },[chatLog])

    //remove specific item from array
    function removeItem(array, valueToRemove) {
        return array.filter(
    	item => item !== valueToRemove);
    }




    //Load all stored chats into local storage


    const clearChatHistory = async (event) => {
        event.preventDefault();
        try{
            const response = await fetch(`http://localhost:8000/clear_chat/${currentChatID}`, {
                method: 'POST'
            });

            if(response.ok){
                console.log(currentChatID)
                console.log(response)
                setChatLog([])
                await getAllStoredChats(setAllCreatedChats)
                
            }
            

            


        }
        catch (error) {
            console.error("Failed to clear chat",error)
        }

    }

    async function createNewChat(event) {
        event.preventDefault();
        setCreatingChat(true)

        //add the new chat to the database
        const response = await fetch("http://localhost:8000/create_new_chat",{
            method: "POST"

        })

        //get the data about the chat and convert to json
        const data = await response.json()
        //get the updated list of chats
        await getAllStoredChats(setAllCreatedChats)

        setCreatingChat(false)

        return data.conversation_id

        

    }





    //function to cancel generating an answer
    const handleCancelResponse= async (event) =>{
        event.preventDefault()

        //set the cancelled reference to true
        cancelledRef.current = true;
        //abort the original API request 
        controllerRef.current?.abort()
 
        //reset states
        setLoading(false)
        setUserInput("")
        streamedTextRef.current = ""
        setChatLog((prev) => {

            //creating shallow copy of chat log and removeing the last two elements (i.e. deleting the last user query and partially generated text from chatbot)
            const updatedChatlog = [...prev].slice(0,-2)

            // const latestUserQuery = updatedChatlog[updatedChatlog.length - 2]

            // //get the latest entry of the chat log (will have the blank text)
            // const latestMessage = updatedChatlog[updatedChatlog.length - 1]
            return updatedChatlog


        }); 

        //get cancel endpoint (with specific query id)
        const cancelEndpoint = `http://localhost:8000/cancel_response/${queryID}`
        fetch(cancelEndpoint,{
            method: "POST"
        }).then(res=>res.json()).then(console.log("cancelled")).catch(err => console.error("Failed to cancel", err));

        //delete that last message generated by the bot and the last query sent by the user from the chat log




        }
    

    async function streamChatbotAnswer(frontendEndToken){

                //get the timestamp for when the message was sent
        const now = new Date().toISOString()
        // Don't allow user to send an empty message
        if (!userInput.trim()) return; 

        const userMessage = { type: 'user', message: userInput,timestamp:String(now) };
        console.log(now)
        
        // update chat log array 
        const newChatLog = [...chatLog, userMessage];
        setChatLog(newChatLog);
        setUserInput('');
        setLoading(true);

        //reset ref

        streamedTextRef.current = ""

            //browser api class which is used to cancel api requests 
            const controller = new AbortController()
            //saving this specific instance of abort controller - can call without rerender - access DOM directly
            //setting the global controller ref to this instance of the abort controller
            controllerRef.current = controller

            //returns an abort signal object instance to communicate with or abort an async operation - in this app, using it for 'cancelling'
            const signal = controllerRef.current.signal;
            cancelledRef.current = false;
    

        try {
            // The API call to our FastAPI backend
            const response = await fetch(`http://localhost:8000/monyai/chat/${frontendEndToken}`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ type: 'user', message: userInput,timestamp:String(now) }),
                signal: signal
            });

            //get the the query ID of the user input
             const chatInputQueryID = response.headers.get("X-Query-ID")


             setQueryID(chatInputQueryID)

            


            if (response.ok){

                //read input data as a stream
                const reader = response.body.getReader()


                //create text decoder to decode binary data into text
                const decoder = new TextDecoder("utf-8")

                //checking to see if streaming done
                let done = false;

                const now =  new Date().toISOString()

                // Add an empty bot message to the chat log before the text streaming starts
                setChatLog(prev => [...prev, { type: 'bot', message: '', timestamp: String(now) }]);

                //while reading from streaming response
                while(!done){

                    //read a chunk of data from the stream
                    const {value, done: readerDone} = await reader.read()

                    //check if we've already read the last chunk in the stream
                    done = readerDone
                    if(done) {

                        break
                    };

                    if(value){
                        //DEcode the chunk
                        const chunkValue = decoder.decode(value,{stream: true})

                        
                        //update the streamed text reference
                        streamedTextRef.current += chunkValue
                        //update the chatlog
                        setChatLog((prev)=>{
                            
                            //creating shallow copy of chat log - avoid mutating state directly for non-primitive typ
                            const updatedChatlog = [...prev]

                            //get the latest entry of the chat log (will have the blank text)
                            const latestMessage = updatedChatlog[updatedChatlog.length - 1]

                            //update the last entry with the streamed text
                            if(latestMessage.type === 'bot'){

                                //filling in  the empty string with the text retrieved from the front end
                                updatedChatlog[updatedChatlog.length - 1] = {
                                    ...latestMessage,
                                    message: streamedTextRef.current
                                }

                            }

                            
                            

                            return updatedChatlog

                            
                        });

                    }


                }


                // Ensure final version of chat is saved after stream finishes - save to local storage for persistence
                setChatLog(prev => {
                const finalChat = [...prev];
                // sessionstorage.setItem('chatLog', JSON.stringify(finalChat));
                return finalChat;
      });
                

            }

            else if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

        } catch (error) {
            console.error('Error fetching chat response:', error);

            //ignore abort errors as this is when the user cancels
            if(!error.name === "AbortError"){
                const now =  new Date().toISOString()
                //if connection fails for any other reason, show in the chat that 'Something went wrong' 
                const errorMessage = { type: 'error', message: 'Sorry, something went wrong. Please try again.',timestamp: String(now) };
                setChatLog(prev => [...prev, errorMessage]);

            }
            
        } finally {
            setLoading(false);
        }


    }
    

    

        



    const handleSubmit = async (event) => {
        event.preventDefault();
        
        // //if chat not yet selected (i.e.e user just starts typing)
        if(!chatSelectedFlag){
            //create a new chat id (the frontend token)
            const newChatID = await createNewChat(event)

            //get the specific chat from the chat history 
            const response = await fetch(`http://localhost:8000/monyai/get_chat_history/${newChatID}`,{
            method: 'POST'

            })

            if (response.ok){
                const data = await response.json()
                setChatLog(data)
                setCurrentChatID(newChatID)

                // send message to newly create chat, stream answer from chatbot
                await streamChatbotAnswer(newChatID)
                

            }
            
            
            setChatSelectedFlag(true)

            }
        else {

            // send message to selected chat, and stream the answer from the chatbot
            await streamChatbotAnswer(currentChatID)

        }

        

    

    };






    return (
        
            <div className='main-chatbot-container'>

                <div className="chat-selection-container">
                    <img  src='/twt-logo.png' className='twt-logo'/> 
                    <button disabled={creatingChat} onClick={(event)=>createNewChat(event)}>
                        + New Chat
                    </button>
                    {creatingChat &&<div className='creating-chat-message'>Creating new chat... </div>}
                    <div className='all-chats-container'>
                        
                        {allCreatedChats.map((storedChat,index)=>(

                                <StoredChat key={String(index)+storedChat.conversation_id} index = {index+1} frontEndToken = {storedChat.conversation_id} setChatLogFunction={setChatLog} setCurrentChatIDFunction={setCurrentChatID} currentChatID={currentChatID} setAllStoredChatsFunction={setAllCreatedChats} currentChatLogState={chatLog} chatSelectedFlag={chatSelectedFlag} setChatSelectedFlagFunction={setChatSelectedFlag} allStoredChatsState={allCreatedChats}/>
                            ))}

                    </div>
                </div>

                
                <div className='chat-area'>
                        
                        <div className='chatbot-title'>Hey, I'm MonyAI your fitness assistant - Ask me anything!</div>

                     

                    <div className="chat-window">
                        {chatLog.map((message, index) => (
                            <div key={`${message.timestamp}-${index}`}>
                                <div className={`message ${message.type}`}>
                                    {message.message}    
                                </div>

                                {<p className='message-timestamp'>{String(message.timestamp).substring(8,10)+ "/"+ String(message.timestamp).substring(5,7)+"/"+String(message.timestamp).substring(0,4)+" "+String(message.timestamp).substring(11,16)}</p> } 
        
                            </div>
                        
                        ))}

                        <div ref={chatWindowBottomRef}></div>
                        
                    </div>

                    {!loading && <button className="cancel-query-button" onClick={clearChatHistory}>Clear chat history</button>}
                    { loading && <button className="cancel-query-button" onClick={handleCancelResponse} type="submit" >Cancel</button>}
                    <form onSubmit={handleSubmit} className="chat-form">

                        <input
                            type="text"
                            value={userInput}
                            onChange={(e) => setUserInput(e.target.value)}
                            placeholder="Enter your question"
                            disabled={loading ||creatingChat}
                        />
                        <button className="send-query-button" type="submit" disabled={creatingChat||loading||userInput==""}><i className="fa-solid fa-paper-plane"></i></button>
                    </form>
                    

                </div>

            </div>

        
        
        
    )

}



export default ChatWindow;