email:
  from: trainwithtaku@gmail.com
  mail_from_username: trainwithtaku
  mail_from_name: TrainwithTaku
  mail_server: smtp.gmail.com
  port: 587
  test_user_email: existing_email@gmail.com


database:
  database_name: trainwithtaku_web
  test_database_name: trainwithtaku_web_test
  user_accounts_collection_name: user_accounts
  vector_store_collection_name: monyai_context_vectors
  chat_collection_name: monyai_chats
  token_blacklist_collection_name: token_blacklist
  mongo_vector_index_name: VectorSearchChatbot
  test_mongo_vector_index_name: VectorSearchTest

  
chatbot:
  top_k: 5
  embedding_model_name: text-embedding-3-large
  llm_version: gpt-4o-mini
  output_token_limit: 2000

auth:
  access_token_expire_minutes: 15
  refresh_token_expire_days: 7
