email:
  mail_from: trainwithtaku@gmail.com
  mail_from_username: trainwithtaku@gmail.com
  mail_from_name: Train with Taku
  # config for Gmail SMTP server - for production, use environment variables to set mail_password and test_user_password
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_start_tls: True
  mail_ssl_tls: False
  test_user_email: existing_email@gmail.com
  dev_email: trainwithtakudev@gmail.com
  welcome_email_file_name: welcome.html


database:
  database_name: trainwithtaku_web
  user_accounts_collection_name: user_accounts
  vector_store_collection_name: monyai_context_vectors
  chat_collection_name: monyai_chats
  token_blacklist_collection_name: token_blacklist
  mongo_vector_index_name: VectorSearchChatbot
  test_mongo_vector_index_name: VectorSearchTest
  test_database_name: trainwithtaku_test
  password_reset_collection_name: password_reset_tokens 
  

  
chatbot:
  top_k: 5
  embedding_model_name: text-embedding-3-large
  llm_version: gpt-4o-mini
  output_token_limit: 1000
  max_n_messages_in_history: 8


auth:
  access_token_expire_minutes: 15
  refresh_token_expire_days: 7
  reset_password_link_expire_minutes: 20

domain:
  frontend_domain_dev: https://trainwithtaku-git-dev-tlm-25s-projects.vercel.app/
  frontend_domain_main: trainwithtaku.com

redis_config:
  host: redis-10505.crce287.eu-west-2-2.ec2.cloud.redislabs.com
  port: 10505
  database_name: trainwithtaku-redis-db
  local_redis_connection_string: "redis://localhost:6379"

  rate_limits:
    login_limit: "10/5minutes"
    chat_limit: "10/1hour"
    sign_up_limit: "5/minute"
    send_password_change_limit: "5/minute"
    reset_password_limit: "5/minute"

blogs:
  blog_collection_name: blogs
  bucket_name: twt-blogs

  


  





