[pytest]
log_cli_level = INFO
log_cli = True
# tests we do not want to run in CI/CD pipeline - only locally
markers = 
    slow: mark tests as slow
    llm_call: mark tests that involve llm calls (that we do not want to in ci)
    rate_limit: test involving rate limit - states can leak in between tests which can affect how tests run. Run rate limit tests in isolation (for now). Do not run in ci
    mongodb: REquires mongodb connection. Skip in CI since  GitHub actions roates IP so whitelisting ip in Mongo is not practical (current workaround - will eventually set up seperat mongo cluster)