[pytest]
log_cli_level = INFO
log_cli = True
# tests we do not want to run in CI/CD pipeline - only locally
markers = 
    slow: mark tests as slow
    llm_call: mark tests that involve llm calls (that we do not want to in ci)